#!/usr/bin/env node
const { startGsnRelay, stopGsnRelay, relayHubAddress } = require( 'localgsn' )

relayUrl= process.env.RELAY_URL
localPort = process.env.LOCAL_PORT
verbose = process.env.VERBOSE

console.log( {relayUrl, localPort, verbose} )
startGsnRelay({relayUrl,localPort, verbose}).then(addr=>console.log( "relay is ready. addr=",addr))
	.catch( err=>{ console.log(err); process.exit() })

process.on('exit', stopGsnRelay )

var done = (function wait () { if (!done) setTimeout(wait, 1000) })();

